
/*****************************************************************************/

/* File Defination :
 *
 * File 		: DIO_config.c
 *
 * Created on	: Sep 8, 2023
 *
 * Author 		: ABDELFATTAH MOAWED
 */
/*****************************************************************************/



#ifndef DIO_CONFIG_H_
#define	DIO_CONFIG_H_

/**
 *  DIO_U8_INTIAL_INPUT
 *  DIO_U8_INTIAL_OUTPUT
 * /
/*DDRA*/
#define DIO_u8_PA0_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PA1_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PA2_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PA3_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PA4_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PA5_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PA6_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PA7_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
/*DDRB*/
#define DIO_u8_PB0_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PB1_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PB2_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PB3_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PB4_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PB5_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PB6_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PB7_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
/*DDRC*/
#define DIO_u8_PC0_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC1_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC2_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC3_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC4_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC5_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC6_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
#define DIO_u8_PC7_INTIAL_DIR	 	DIO_U8_INTIAL_OUTPUT
/*DDRD*/
#define DIO_u8_PD0_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD1_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD2_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD3_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD4_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD5_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD6_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#define DIO_u8_PD7_INTIAL_DIR	 	DIO_U8_INTIAL_INPUT
#endif /* DIO_PRIVATE_H_ */
